### ISSUE TITLE
Authentication failed on last.fm

### ISSUE THREAD

**Issue by xmalbertox** [InputUsername/rescrobbled#65]
Hi, getting an "authentication failed" error:

```
Failed to authenticate with Last.fm

Caused by:
    Authentication failed: Non Success status (403)
```

My config is simply:
```toml
lastfm-key = "bc7...b42"
lastfm-secret = "02b...591"
player-whitelist = ["mpd"]
```

The user and pass is correct and working, tested both on the website and other applications.
