### ISSUE TITLE
Not scrobbling, stuck at "Looking for an active MPRIS player..."

### ISSUE THREAD

**Issue by TheLastZombie** [InputUsername/rescrobbled#93]
rescrobbled doesn't seem to detect any of my MPRIS-supported players. Instead, when I launch it, it gets "stuck" after the following:

```
Authenticated with Last.fm successfully!
Authenticated with ListenBrainz successfully!
Looking for an active MPRIS player...
```

I tried playing music via DeaDBeeF, MPD, Psst and Spotify, but to no avail. The player <-> MPRIS connection works fine:

```
$ playerctl metadata
spotify mpris:trackid             /com/spotify/track/2G7GkzbmU5PTNs2lGlaAu9
spotify mpris:length              211826000
spotify mpris:artUrl              https://i.scdn.co/image/ab67616d0000b273666c1a7abbf10f2f6e4aa082
spotify xesam:album               Three Cheers for Disappointment
spotify xesam:albumArtist         The Arrogant Sons Of Bitches
spotify xesam:artist              The Arrogant Sons Of Bitches
spotify xesam:autoRating          0.26000000000000001
spotify xesam:discNumber          1
spotify xesam:title               1-800-Alarm-Me
spotify xesam:trackNumber         7
spotify xesam:url                 https://open.spotify.com/track/2G7GkzbmU5PTNs2lGlaAu9
```

My configuration file:

```TOML
lastfm-key = "<redacted>"
lastfm-secret = "<redacted>"
player-whitelist = [ "DeaDBeeF", "mpd", "psst", "spotify" ]

[[listenbrainz]]
token = "<redacted>"
```

I'm using the binary from the release page (version 0.6.2).
